ALTER TABLE raw_afs_articles
    ADD COLUMN image_1 VARCHAR(255) NULL AFTER online_flag,
    ADD COLUMN image_2 VARCHAR(255) NULL AFTER image_1,
    ADD COLUMN image_3 VARCHAR(255) NULL AFTER image_2,
    ADD COLUMN image_4 VARCHAR(255) NULL AFTER image_3,
    ADD COLUMN image_5 VARCHAR(255) NULL AFTER image_4,
    ADD COLUMN image_6 VARCHAR(255) NULL AFTER image_5,
    ADD COLUMN image_7 VARCHAR(255) NULL AFTER image_6,
    ADD COLUMN image_8 VARCHAR(255) NULL AFTER image_7,
    ADD COLUMN image_9 VARCHAR(255) NULL AFTER image_8,
    ADD COLUMN image_10 VARCHAR(255) NULL AFTER image_9;
