<?php

return [
    'app_name' => 'Wela Sync Admin',
    'default_per_page' => 20,
    'max_per_page' => 100,
    'stage_tables' => [
        'raw_afs_articles' => 'AFS Artikel (Raw)',
        'raw_afs_categories' => 'AFS Kategorien (Raw)',
        'raw_extra_article_translations' => 'Extra Artikel-Uebersetzungen',
        'raw_extra_category_translations' => 'Extra Kategorie-Uebersetzungen',
        'stage_products' => 'Stage Produkte',
        'stage_product_translations' => 'Stage Produkt-Uebersetzungen',
        'stage_product_documents' => 'Stage Produkt-Dokumente',
        'stage_product_media' => 'Stage Produkt-Medien',
        'stage_categories' => 'Stage Kategorien',
        'stage_category_translations' => 'Stage Kategorie-Uebersetzungen',
        'stage_attribute_translations' => 'Stage Attribut-Uebersetzungen',
        'xt_products_snapshot' => 'XT Produkt Snapshot',
        'xt_categories_snapshot' => 'XT Kategorie Snapshot',
        'xt_media_snapshot' => 'XT Medien Snapshot',
        'xt_documents_snapshot' => 'XT Dokumente Snapshot',
        'xt_mirror_products' => 'XT Mirror Produkte',
        'xt_mirror_categories' => 'XT Mirror Kategorien',
        'xt_mirror_categories_description' => 'XT Mirror Kategorie-Uebersetzungen',
        'xt_mirror_products_description' => 'XT Mirror Produkt-Uebersetzungen',
        'xt_mirror_products_to_categories' => 'XT Mirror Produkt-Kategorien',
        'xt_mirror_media' => 'XT Mirror Medien',
        'xt_mirror_media_link' => 'XT Mirror Medien-Links',
        'xt_mirror_plg_products_attributes' => 'XT Mirror Attribute',
        'xt_mirror_plg_products_attributes_description' => 'XT Mirror Attribut-Uebersetzungen',
        'xt_mirror_plg_products_to_attributes' => 'XT Mirror Produkt-Attribute',
        'xt_mirror_seo_url' => 'XT Mirror SEO-URLs',
        'export_queue' => 'Export Queue',
        'product_export_state' => 'Produkt Export State',
        'product_media_export_state' => 'Produkt Medien Export State',
        'product_document_export_state' => 'Produkt Dokument Export State',
    ],
];
