<?php

return [
    'export_queue_entities' => [
        'category_export_queue',
        'product_export_queue',
        'media_export_queue',
        'document_export_queue',
    ],

    'category_export_queue' => [
        'label' => 'Kategorie',
        'entity_type' => 'category',
        'queue_table' => 'export_queue',
        'queue_insert_batch_size' => 200,
        'worker_batch_size' => 5000,
        'worker_max_attempts' => 3,
        'worker_retry_delay_seconds' => 300,
        'stage_table' => 'stage_categories',
        'translation_table' => 'stage_category_translations',
        'state_table' => 'category_export_state',
        'identity_field' => 'afs_wg_id',
        'state_identity_field' => 'category_id',
        'hash_field' => 'hash',
        'state_hash_field' => 'last_exported_hash',
        'state_last_seen_field' => 'last_seen_at',
        'removed_hash_value' => 'offline',
        'removed_payload' => [
            'online_flag' => 0,
        ],
        'monitor_source' => 'delta_categories',
        'mirror_compare_fields' => [
            'category.afs_wg_id' => 'external_id',
            'category.parent_afs_id' => 'parent_afs_id',
            'category.image' => 'image',
            'category.header_image' => 'header_image',
            'category.online_flag' => 'online_flag',
        ],
        'mirror_translation_hash_field' => 'translation_hash',
        'mirror_seo_hash_field' => 'seo_hash',
        'mirror_require_success_run' => true,
        'entity_order_by' => ['level ASC', 'afs_wg_id ASC'],
        'hash_fields' => [
            'afs_wg_id',
            'parent_afs_id',
            'name_default',
            'description_default',
            'image',
            'header_image',
            'online_flag',
        ],
    ],

    'product_export_queue' => [
        'label' => 'Produkt',
        'entity_type' => 'product',
        'queue_table' => 'export_queue',
        'queue_insert_batch_size' => 50,
        'worker_batch_size' => 5000,
        'worker_max_attempts' => 3,
        'worker_retry_delay_seconds' => 300,
        'stage_table' => 'stage_products',
        'translation_table' => 'stage_product_translations',
        'attribute_table' => 'stage_attribute_translations',
        'state_table' => 'product_export_state',
        'identity_field' => 'afs_artikel_id',
        'state_identity_field' => 'product_id',
        'hash_field' => 'hash',
        'state_hash_field' => 'last_exported_hash',
        'state_last_seen_field' => 'last_seen_at',
        'removed_hash_value' => 'offline',
        'removed_payload' => [
            'online' => 0,
        ],
        'monitor_source' => 'delta_products',
        'mirror_compare_fields' => [
            'product.sku' => 'sku',
            'product.ean' => 'ean',
            'product.stock' => 'stock',
            'product.price' => 'price',
            'product.weight' => 'weight',
            'product.online_flag' => 'online_flag',
            'product.is_master' => 'is_master',
            'product.master_sku' => 'master_sku',
            'product.category_afs_id' => 'category_afs_id',
        ],
        'mirror_translation_hash_field' => 'translation_hash',
        'mirror_attribute_hash_field' => 'attribute_hash',
        'mirror_seo_hash_field' => 'seo_hash',
        'mirror_require_success_run' => true,
        'hash_fields' => [
            'afs_artikel_id',
            'sku',
            'name_default',
            'description_default',
            'short_description_default',
            'ean',
            'stock',
            'price',
            'weight',
            'category_afs_id',
            'category_name',
            'tax_rate',
            'unit',
            'min_qty',
            'variant_flag',
            'product_type',
            'is_master',
            'is_slave',
            'is_standard',
            'master_sku',
            'online_flag',
        ],
    ],

    'media_export_queue' => [
        'label' => 'Medien',
        'entity_type' => 'media',
        'queue_table' => 'export_queue',
        'queue_insert_batch_size' => 200,
        'worker_batch_size' => 5000,
        'worker_max_attempts' => 3,
        'worker_retry_delay_seconds' => 300,
        'stage_table' => 'stage_product_media',
        'state_table' => 'product_media_export_state',
        'identity_field' => 'media_external_id',
        'state_identity_field' => 'entity_id',
        'hash_field' => 'hash',
        'state_hash_field' => 'last_exported_hash',
        'state_last_seen_field' => 'last_seen_at',
        'removed_hash_value' => 'removed',
        'removed_payload' => [
            'deleted' => 1,
        ],
        'monitor_source' => 'delta_media',
        'mirror_require_success_run' => true,
        'mirror_compare_fields' => [
            'media_external_id' => 'media_external_id',
            'afs_artikel_id' => 'afs_artikel_id',
            'file_name' => 'file_name',
            'type' => 'media_type',
            'sort_order' => 'sort_order',
        ],
        'payload_fields' => [
            'media_external_id',
            'afs_artikel_id',
            'source_slot',
            'file_name',
            'path',
            'type',
            'document_type',
            'sort_order',
            'position',
        ],
    ],

    'document_export_queue' => [
        'label' => 'Dokument',
        'entity_type' => 'document',
        'queue_table' => 'export_queue',
        'queue_insert_batch_size' => 200,
        'worker_batch_size' => 5000,
        'worker_max_attempts' => 3,
        'worker_retry_delay_seconds' => 300,
        'stage_table' => 'stage_product_documents',
        'state_table' => 'product_document_export_state',
        'identity_field' => 'afs_document_id',
        'state_identity_field' => 'entity_id',
        'hash_field' => 'hash',
        'state_hash_field' => 'last_exported_hash',
        'state_last_seen_field' => 'last_seen_at',
        'removed_hash_value' => 'removed',
        'removed_payload' => [
            'deleted' => 1,
        ],
        'monitor_source' => 'delta_documents',
        'mirror_require_success_run' => true,
        'mirror_compare_fields' => [
            'afs_document_id' => 'afs_document_id',
            'afs_artikel_id' => 'afs_artikel_id',
            'file_name' => 'file_name',
            'document_type' => 'document_type',
            'sort_order' => 'sort_order',
        ],
        'payload_fields' => [
            'afs_document_id',
            'afs_artikel_id',
            'title',
            'file_name',
            'path',
            'source_path',
            'document_type',
            'sort_order',
            'position',
        ],
    ],
];
