<?php

return [
    'write' => [
        'xt_categories' => [
            'type' => 'entity',
            'table' => 'xt_categories',
            'base' => 'stage_categories',
            'primary_key' => 'categories_id',
            'identity' => [
                'target_field' => 'external_id',
                'source_field' => 'afs_wg_id',
            ],
            'on_found' => 'update_if_changed',
            'on_missing' => 'insert',
            'columns' => [
                'external_id' => 'stage.afs_wg_id',
                'permission_id' => 'const:null',
                'categories_owner' => 'const:1',
                'categories_image' => 'stage.image',
                'categories_left' => 'calc:nested_set_left',
                'categories_right' => 'calc:nested_set_right',
                'categories_level' => 'calc:category_level',
                'parent_id' => 'calc:category_parent_id',
                'categories_status' => 'calc:category_status',
                'categories_template' => 'const:""',
                'listing_template' => 'const:""',
                'sort_order' => 'const:0',
                'products_sorting' => 'const:""',
                'products_sorting2' => 'const:""',
                'top_category' => 'calc:is_top_category',
                'start_page_category' => 'const:0',
                'date_added' => 'calc:now_if_insert',
                'last_modified' => 'calc:now',
                'category_custom_link' => 'const:0',
                'category_custom_link_type' => 'const:""',
                'category_custom_link_id' => 'const:0',
                'google_product_cat' => 'const:0',
                'categories_master_image' => 'stage.header_image',
            ],
        ],

        'xt_categories_description' => [
            'type' => 'multilang_child',
            'table' => 'xt_categories_description',
            'base' => 'stage_categories',
            'languages' => ['de', 'en', 'fr', 'nl'],
            'primary_key' => ['categories_id', 'language_code'],
            'identity' => [
                'categories_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                'language_code' => 'context:language_code',
            ],
            'on_found' => 'update_if_changed',
            'on_missing' => 'insert',
            'columns_by_language' => [
                'de' => [
                    'categories_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                    'language_code' => 'const:"de"',
                    'categories_name' => 'translation.name',
                    'categories_heading_title' => 'translation.name',
                    'categories_description' => 'translation.description',
                    'categories_description_bottom' => 'const:""',
                    'categories_store_id' => 'const:1',
                ],
                'en' => [
                    'categories_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                    'language_code' => 'const:"en"',
                    'categories_name' => 'translation.name',
                    'categories_heading_title' => 'translation.name',
                    'categories_description' => 'translation.description',
                    'categories_description_bottom' => 'const:""',
                    'categories_store_id' => 'const:1',
                ],
                'fr' => [
                    'categories_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                    'language_code' => 'const:"fr"',
                    'categories_name' => 'translation.name',
                    'categories_heading_title' => 'translation.name',
                    'categories_description' => 'translation.description',
                    'categories_description_bottom' => 'const:""',
                    'categories_store_id' => 'const:1',
                ],
                'nl' => [
                    'categories_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                    'language_code' => 'const:"nl"',
                    'categories_name' => 'translation.name',
                    'categories_heading_title' => 'translation.name',
                    'categories_description' => 'translation.description',
                    'categories_description_bottom' => 'const:""',
                    'categories_store_id' => 'const:1',
                ],
            ],
        ],

        'xt_products' => [
            'type' => 'entity',
            'table' => 'xt_products',
            'base' => 'stage_products',
            'primary_key' => 'products_id',
            'identity' => [
                'target_field' => 'external_id',
                'source_field' => 'afs_artikel_id',
            ],
            'on_found' => 'update_if_changed',
            'on_missing' => 'insert',
            'columns' => [
                'external_id'                     => 'stage.afs_artikel_id',
                'permission_id'                   => 'const:0',
                'products_owner'                  => 'const:0',
                'products_ean'                    => 'stage.ean',
                'products_quantity'               => 'stage.stock',
                'show_stock'                      => 'const:0',
                'products_average_quantity'       => 'const:0',
                'products_shippingtime'           => 'stage.min_qty',
                'products_shippingtime_nostock'   => 'const:""',
                'products_model'                  => 'stage.sku',
                'products_master_flag'            => 'stage.is_master',
                'products_master_model'           => 'stage.master_sku',
                'ms_open_first_slave'             => 'const:2',
                'ms_show_slave_list'              => 'const:2',
                'ms_filter_slave_list'            => 'const:2',
                'ms_filter_slave_list_hide_on_product' => 'const:2',
                'products_image_from_master'      => 'const:2',
                'ms_load_masters_free_downloads'  => 'const:2',
                'ms_load_masters_main_img'        => 'const:2',
                'products_price'                  => 'calc:product_price',
                'date_added'                      => 'calc:now_if_insert',
                'last_modified'                   => 'calc:now',
                'products_weight'                 => 'stage.weight',
                'products_status'                 => 'calc:product_status',
                'products_tax_class_id'           => 'calc:tax_class_id',
                'products_unit'                   => 'calc:product_unit',
                'products_average_rating'         => 'const:0',
                'products_rating_count'           => 'const:0',
                'products_digital'                => 'const:0',
                'flag_has_specials'               => 'const:0',
                'products_serials'                => 'const:0',
                'total_downloads'                 => 'const:0',
                'group_discount_allowed'          => 'const:1',
                'google_product_cat'              => 'const:""',
                'products_canonical_master'       => 'const:0',
            ],
        ],

        'xt_products_description' => [
            'type' => 'multilang_child',
            'table' => 'xt_products_description',
            'base' => 'stage_products',
            'languages' => ['de', 'en', 'fr', 'nl'],
            'primary_key' => ['products_id', 'language_code'],
            'identity' => [
                'products_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                'language_code' => 'context:language_code',
            ],
            'on_found' => 'update_if_changed',
            'on_missing' => 'insert',
            'columns_by_language' => [
                'de' => [
                    'products_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                    'language_code' => 'translation.language_code',
                    'reload_st' => 'const:0',
                    'products_name' => 'translation.name',
                    'products_description' => 'calc:product_translation_description',
                    'products_short_description' => 'translation.short_description',
                    'products_keywords' => 'const:""',
                    'products_url' => 'const:""',
                    'products_store_id' => 'const:1',
                ],
                'en' => [
                    'products_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                    'language_code' => 'translation.language_code',
                    'reload_st' => 'const:0',
                    'products_name' => 'translation.name',
                    'products_description' => 'calc:product_translation_description',
                    'products_short_description' => 'translation.short_description',
                    'products_keywords' => 'const:""',
                    'products_url' => 'const:""',
                    'products_store_id' => 'const:1',
                ],
                'fr' => [
                    'products_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                    'language_code' => 'translation.language_code',
                    'reload_st' => 'const:0',
                    'products_name' => 'translation.name',
                    'products_description' => 'calc:product_translation_description',
                    'products_short_description' => 'translation.short_description',
                    'products_keywords' => 'const:""',
                    'products_url' => 'const:""',
                    'products_store_id' => 'const:1',
                ],
                'nl' => [
                    'products_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                    'language_code' => 'translation.language_code',
                    'reload_st' => 'const:0',
                    'products_name' => 'translation.name',
                    'products_description' => 'calc:product_translation_description',
                    'products_short_description' => 'translation.short_description',
                    'products_keywords' => 'const:""',
                    'products_url' => 'const:""',
                    'products_store_id' => 'const:1',
                ],
            ],
        ],

        'xt_products_to_categories' => [
            'type' => 'relation',
            'table' => 'xt_products_to_categories',
            'base' => 'stage_products',
            'replace_by' => ['products_id'],
            'delete_match_columns' => ['products_id'],
            'columns' => [
                'products_id'   => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                'categories_id' => 'ref:xt_categories.categories_id by external_id=stage.category_afs_id',
                'master_link'   => 'const:1',
                'store_id'      => 'const:1',
            ],
        ],

        'xt_plg_products_attributes' => [
            'type' => 'entity',
            'table' => 'xt_plg_products_attributes',
            'base' => 'stage_attribute_translations',
            'primary_key' => 'attributes_id',
            'identity' => [
                'target_field' => 'attributes_model',
                'source_field' => 'attribute_model',
            ],
            'on_found' => 'update_if_changed',
            'on_missing' => 'insert',
            'columns' => [
                'attributes_parent' => 'attribute.attributes_parent',
                'attributes_model' => 'attribute.attribute_model',
                'attributes_templates_id' => 'const:1',
                'sort_order' => 'attribute.sort_order',
                'status' => 'const:1',
            ],
        ],

        'xt_plg_products_attributes_description' => [
            'type' => 'child',
            'table' => 'xt_plg_products_attributes_description',
            'base' => 'stage_attribute_translations',
            'primary_key' => ['attributes_id', 'language_code'],
            'columns' => [
                'attributes_id' => 'ref:xt_plg_products_attributes.attributes_id by attributes_model=attribute.attribute_model',
                'language_code' => 'attribute.language_code',
                'attributes_name' => 'attribute.display_name',
                'attributes_desc' => 'const:""',
            ],
        ],

        'xt_plg_products_to_attributes' => [
            'type' => 'relation',
            'table' => 'xt_plg_products_to_attributes',
            'base' => 'stage_attribute_translations',
            'replace_by' => ['products_id'],
            'delete_match_columns' => ['products_id'],
            'columns' => [
                'products_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                'attributes_id' => 'ref:xt_plg_products_attributes.attributes_id by attributes_model=attribute.attribute_model',
                'attributes_parent_id' => 'attribute.attributes_parent_id',
            ],
        ],

        'xt_media' => [
            'type' => 'entity',
            'table' => 'xt_media',
            'base' => 'stage_product_media',
            'primary_key' => 'id',
            'identity' => [
                'target_field' => 'external_id',
                'source_field' => 'media_external_id',
            ],
            'on_found' => 'update_if_changed',
            'on_missing' => 'insert',
            'columns' => [
                'file' => 'stage.file_name',
                'type' => 'stage.type',
                'class' => 'const:"product"',
                'download_status' => 'const:"free"',
                'status' => 'const:1',
                'owner' => 'const:1',
                'date_added' => 'calc:now_if_insert',
                'last_modified' => 'calc:now',
                'max_dl_count' => 'const:"0"',
                'max_dl_days' => 'const:"0"',
                'total_downloads' => 'const:0',
                'copyright_holder' => 'const:""',
                'external_id' => 'stage.media_external_id',
            ],
        ],

        'xt_media_link_images' => [
            'type' => 'relation',
            'table' => 'xt_media_link',
            'base' => 'stage_product_media',
            'replace_by' => ['link_id', 'type'],
            'identity_columns' => ['m_id', 'link_id', 'type'],
            'delete_match_columns' => ['m_id', 'type'],
            'filter' => [
                'type' => 'images',
            ],
            'columns' => [
                'm_id' => 'ref:xt_media.id by external_id=stage.media_external_id',
                'link_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                'class' => 'const:"product"',
                'type' => 'const:"images"',
                'sort_order' => 'stage.position',
            ],
        ],

        'xt_media_documents' => [
            'type' => 'entity',
            'table' => 'xt_media',
            'base' => 'stage_product_documents',
            'primary_key' => 'id',
            'identity' => [
                'target_field' => 'external_id',
                'source_field' => 'afs_document_id',
            ],
            'on_found' => 'update_if_changed',
            'on_missing' => 'insert',
            'columns' => [
                'file' => 'stage.file_name',
                'type' => 'const:"files"',
                'class' => 'const:"product"',
                'download_status' => 'const:"free"',
                'status' => 'const:1',
                'owner' => 'const:1',
                'date_added' => 'calc:now_if_insert',
                'last_modified' => 'calc:now',
                'max_dl_count' => 'const:"0"',
                'max_dl_days' => 'const:"0"',
                'total_downloads' => 'const:0',
                'copyright_holder' => 'const:""',
                'external_id' => 'stage.afs_document_id',
            ],
        ],

        'xt_media_link_documents' => [
            'type' => 'relation',
            'table' => 'xt_media_link',
            'base' => 'stage_product_documents',
            'replace_by' => ['link_id', 'type'],
            'identity_columns' => ['m_id', 'link_id', 'type'],
            'delete_match_columns' => ['m_id', 'type'],
            'columns' => [
                'm_id' => 'ref:xt_media.id by external_id=stage.afs_document_id',
                'link_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                'class' => 'const:"product"',
                'type' => 'const:"media"',
                'sort_order' => 'stage.position',
            ],
        ],

        'xt_seo_url_products' => [
            'type' => 'seo',
            'table' => 'xt_seo_url',
            'base' => 'stage_products',
            'languages' => ['de', 'en', 'fr', 'nl'],
            'identity' => [
                'link_type' => 'const:1',
                'link_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                'language_code' => 'context:language_code',
                'store_id' => 'const:1',
            ],
            'policy' => [
                'preserve_existing_url' => true,
                'generate_url_if_missing' => true,
                'ensure_unique_url' => true,
                'use_category_path' => true,
                'path_depth' => 'unlimited',
            ],
            'columns_by_language' => [
                'de' => [
                    'url_text' => 'calc:product_seo_url_de',
                    'url_md5' => 'calc:product_seo_url_md5_de',
                    'language_code' => 'const:"de"',
                    'link_type' => 'const:1',
                    'link_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                    'meta_title' => 'translation.meta_title',
                    'meta_description' => 'translation.meta_description',
                    'meta_keywords' => 'const:""',
                    'store_id' => 'const:1',
                ],
                'en' => [
                    'url_text' => 'calc:product_seo_url_en',
                    'url_md5' => 'calc:product_seo_url_md5_en',
                    'language_code' => 'const:"en"',
                    'link_type' => 'const:1',
                    'link_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                    'meta_title' => 'translation.meta_title',
                    'meta_description' => 'translation.meta_description',
                    'meta_keywords' => 'const:""',
                    'store_id' => 'const:1',
                ],
                'fr' => [
                    'url_text' => 'calc:product_seo_url_fr',
                    'url_md5' => 'calc:product_seo_url_md5_fr',
                    'language_code' => 'const:"fr"',
                    'link_type' => 'const:1',
                    'link_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                    'meta_title' => 'translation.meta_title',
                    'meta_description' => 'translation.meta_description',
                    'meta_keywords' => 'const:""',
                    'store_id' => 'const:1',
                ],
                'nl' => [
                    'url_text' => 'calc:product_seo_url_nl',
                    'url_md5' => 'calc:product_seo_url_md5_nl',
                    'language_code' => 'const:"nl"',
                    'link_type' => 'const:1',
                    'link_id' => 'ref:xt_products.products_id by external_id=stage.afs_artikel_id',
                    'meta_title' => 'translation.meta_title',
                    'meta_description' => 'translation.meta_description',
                    'meta_keywords' => 'const:""',
                    'store_id' => 'const:1',
                ],
            ],
        ],

        'xt_seo_url_categories' => [
            'type' => 'seo',
            'table' => 'xt_seo_url',
            'base' => 'stage_categories',
            'languages' => ['de', 'en', 'fr', 'nl'],
            'identity' => [
                'link_type' => 'const:2',
                'link_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                'language_code' => 'context:language_code',
                'store_id' => 'const:1',
            ],
            'policy' => [
                'preserve_existing_url' => true,
                'generate_url_if_missing' => true,
                'ensure_unique_url' => true,
                'path_depth' => 'unlimited',
            ],
            'columns_by_language' => [
                'de' => [
                    'url_text' => 'calc:category_seo_url_de',
                    'url_md5' => 'calc:category_seo_url_md5_de',
                    'language_code' => 'const:"de"',
                    'link_type' => 'const:2',
                    'link_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                    'meta_title' => 'translation.meta_title',
                    'meta_description' => 'translation.meta_description',
                    'meta_keywords' => 'const:""',
                    'store_id' => 'const:1',
                ],
                'en' => [
                    'url_text' => 'calc:category_seo_url_en',
                    'url_md5' => 'calc:category_seo_url_md5_en',
                    'language_code' => 'const:"en"',
                    'link_type' => 'const:2',
                    'link_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                    'meta_title' => 'translation.meta_title',
                    'meta_description' => 'translation.meta_description',
                    'meta_keywords' => 'const:""',
                    'store_id' => 'const:1',
                ],
                'fr' => [
                    'url_text' => 'calc:category_seo_url_fr',
                    'url_md5' => 'calc:category_seo_url_md5_fr',
                    'language_code' => 'const:"fr"',
                    'link_type' => 'const:2',
                    'link_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                    'meta_title' => 'translation.meta_title',
                    'meta_description' => 'translation.meta_description',
                    'meta_keywords' => 'const:""',
                    'store_id' => 'const:1',
                ],
                'nl' => [
                    'url_text' => 'calc:category_seo_url_nl',
                    'url_md5' => 'calc:category_seo_url_md5_nl',
                    'language_code' => 'const:"nl"',
                    'link_type' => 'const:2',
                    'link_id' => 'ref:xt_categories.categories_id by external_id=stage.afs_wg_id',
                    'meta_title' => 'translation.meta_title',
                    'meta_description' => 'translation.meta_description',
                    'meta_keywords' => 'const:""',
                    'store_id' => 'const:1',
                ],
            ],
        ],
    ],
];
